export const FIELD_NAME = {
  TAG_NUMBER: 'AddObservation/TagNumber',
  TAG_TYPE: 'AddObservation/TagType',
  PHOTOS: 'AddObservation/photos',
  PHOTO: 'AddObservation/photo',
  RINGS: 'AddObservation/rings',
  TYPE_OF_BIRD: 'AddObservation/typeOfBird',
  BIRD_SEX: 'AddObservation/birdSex',
  BIRD_AGE: 'AddObservation/birdAge',
  BIRD_WAS: 'AddObservation/birdWas',
  BIRD_STATUS: 'AddObservation/birdStatus',
  LOCATION_CONDITION: 'AddObservation/locationСondition',
  PLACE: 'AddObservation/place',
  COORDINATE_ACCURACY: 'AddObservation/coordinateAccuracy',
  DATE: 'AddObservation/date',
  DATE_ACCURACY: 'AddObservation/dateAccuracy',
}
