enum PATHS {
  APP_STACK = 'APP_STACK',
  LOGIN_STACK = 'LOGIN_STACK',
  INTRODUCTION_STACK = 'INTRODUCTION_STACK',
  APP_LOADING_SCREEN = 'APP_LOADING_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  REGISTRATION_SCREEN = 'REGISTRATION_SCREEN',
  REGISTRATION_NOTIFICATION_SCREEN = 'REGISTRATION_NOTIFICATION_SCREEN',
  PASSWORD_RECOVERY = 'PASSWORD_RECOVERY',
  LANGUAGE_SCREEN = 'LANGUAGE_SCREEN',
  INTRODUCTION_SCREEN = 'INTRODUCTION_SCREEN',
  ADD_OBSERVATION = 'ADD_OBSERVATION',
  OBSERVATION_CREATED = 'OBSERVATION_CREATED',
  ADD_PLACE = 'ADD_PLACE',
  PLACES = 'PLACES',
  MAP_SCREEN = 'MAP_SCREEN',
  OBSERVATIONS_SCREEN = 'OBSERVATIONS_SCREEN',
  SETTINGS_SCREEN = 'SETTINGS_SCREEN',
  ABOUT_APP_SCREEN = 'ABOUT_APP_SCREEN',
}

export default PATHS
