export const APP_LOADING_SCREEN = 'APP_LOADING_SCREEN';
export const MAIN_SCREEN = 'MAIN_SCREEN';
export const APP_STACK = 'APP_STACK';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTRATION_SCREEN = 'REGISTRATION_SCREEN';
export const REGISTRATION_NOTIFICATION_SCREEN = 'REGISTRATION_NOTIFICATION_SCREEN';
export const PASSWORD_RECOVERY = 'PASSWORD_RECOVERY';
export const LOGIN_STACK = 'LOGIN_STACK';
